<?php

namespace Modules\Assistance\Controllers;

use App\Http\Controllers\Controller;
use Modules\Assistance\Models\Assistance;
use Illuminate\Http\Request;
use Modules\Assistance\Models\AssistanceCategory;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use DB;
use Illuminate\Support\Facades\Auth;
use Modules\Booking\Events\BookingConfirmEvent;
use Modules\Booking\Models\Booking;
use Modules\Booking\Models\BookingMessage;

class AssistanceController extends Controller
{
    protected $assistanceClass;
    protected $locationClass;
    protected $assistanceCategoryClass;
    protected $attributesClass;

    public function __construct(Assistance $assistance)
    {
        $this->assistanceClass = $assistance;
        $this->locationClass = Location::class;
        $this->assistanceCategoryClass = AssistanceCategory::class;
        $this->attributesClass = Attributes::class;
    }
    public function callAction($method, $parameters)
    {
        if (setting_item('assistance_disable')) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $layout = setting_item("assistance_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        $is_ajax = $request->query('_ajax');
        $for_map = $request->query('_map', $layout === 'map');

        if (!empty($request->query('limit'))) {
            $limit = $request->query('limit');
        } else {
            $limit = !empty(setting_item("assistance_page_limit_item")) ? setting_item("assistance_page_limit_item") : 9;
        }
        $query = $this->assistanceClass->search($request->input());
        $list = $query->paginate($limit);

        $markers = [];
        if (!empty($list) and $for_map) {
            foreach ($list as $row) {
                $markers[] = [
                    "id" => $row->id,
                    "title" => $row->title,
                    "lat" => (float)$row->map_lat,
                    "lng" => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Assistance::frontend.layouts.search.loop-grid', ['row' => $row, 'disable_lazyload' => 1, 'wrap_class' => 'infobox-item'])->render(),
                    'marker' => get_file_url(setting_item("assistance_icon_marker_map"), 'full') ?? url('images/icons/png/pin.png'),
                ];
            }
        }
        $limit_location = 15;
        if (empty(setting_item("assistance_location_search_style")) or setting_item("assistance_location_search_style") == "normal") {
            $limit_location = 1000;
        }
        $data = [
            'rows' => $list,
            'layout' => $layout
        ];
        if ($is_ajax) {
            return $this->sendSuccess([
                "markers" => $markers,
                'fragments' => [
                    '.ajax-search-result' => view('Assistance::frontend.ajax.search-result' . ($for_map ? '-map' : ''), $data)->render(),
                    '.result-count' => $list->total() ? ($list->total() > 1 ? __(":count de serviços encontradas", ['count' => $list->total()]) : __(":count de serviço encontrada", ['count' => $list->total()])) : '',
                    '.count-string' => $list->total() ? __("Mostrando :from - :to of :total serviços", ["from" => $list->firstItem(), "to" => $list->lastItem(), "total" => $list->total()]) : ''
                ]
            ]);
        }
        $data = [
            'rows' => $list,
            'assistance_category' => $this->assistanceCategoryClass::where('status', 'publish')->with(['translation'])->get()->toTree(),
            'assistance_location' => $this->locationClass::where('status', 'publish')->with(['translation'])->limit($limit_location)->get()->toTree(),
            'assistance_min_max_price' => $this->assistanceClass::getMinMaxPrice(),
            'markers' => $markers,
            "blank" => setting_item('search_open_tab') == "current_tab" ? 0 : 1,
            "seo_meta" => $this->assistanceClass::getSeoMetaForPageList(),
            'layout' => $layout
        ];
        $data['attributes'] = $this->attributesClass::where('service', 'assistance')->orderBy("position", "desc")->with(['terms' => function ($query) {
            $query->withCount('assistance');
        }, 'translation'])->get();
        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Assistance::frontend.search-map', $data);
        }
        return view('Assistance::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->assistanceClass::where('slug', $slug)->with(['location', 'translation', 'hasWishList'])->first();
        if (empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }
        $translation = $row->translate();
        $tour_related = [];
        $location_id = $row->location_id;
        $assistance_related = null;
        if (!empty($location_id)) {
            $assistance_related = $this->assistanceClass::where('location_id', $location_id)->where("status", "publish")->take($this->limitRelated ?? 4)->whereNotIn('id', [$row->id])->with(['location', 'translation', 'hasWishList'])->get();
        }
        $review_list = $row->getReviewList();

        $data = [
            'row' => $row,
            'translation' => $translation,
            'assistance_related' => $assistance_related,
            'booking_data' => $row->getBookingData(),
            'review_list' => $review_list,
            'seo_meta' => $row->getSeoMetaWithTranslation(app()->getLocale(), $translation),
            'body_class' => 'is_single',
            'breadcrumbs'       => [
                [
                    'name'  => __('Serviços'),
                    'url'  => route('assistance.search'),
                ],
            ],
        ];
        $data['breadcrumbs'] = array_merge($data['breadcrumbs'], $row->locationBreadcrumbs());
        $data['breadcrumbs'][] = [
            'name'  => $translation->title,
            'class' => 'active'
        ];
        $this->setActiveMenu($row);
        return view('Assistance::frontend.detail', $data);
    }

    public function booking(Request $request, $id)
    {
        // Validação explícita do ID
        if (!is_numeric($id)) {
            abort(404);
        }

        /** @var Assistance $assistance */
        $assistance = Assistance::query()
            ->where('id', (int) $id)
            ->where('status', 'publish')
            ->firstOrFail();

        // --------------------
        // BASE
        // --------------------
        $total = 0;
        $total_guests = 0;

        $base_price = (
            $assistance->sale_price &&
            $assistance->sale_price > 0 &&
            $assistance->sale_price < $assistance->price
        )
            ? $assistance->sale_price
            : $assistance->price;

        $total = $base_price;
        $total_before_fees = $total;

        // --------------------
        // FEES (ADMIN)
        // --------------------
        $total_buyer_fee = 0;
        $list_buyer_fees = setting_item('assistance_booking_buyer_fees');

        if (!empty($list_buyer_fees)) {
            $list_fees = json_decode($list_buyer_fees, true);
            $total_buyer_fee = $assistance->calculateServiceFees(
                $list_fees,
                $total_before_fees,
                $total_guests
            );
            $total += $total_buyer_fee;
        }

        // --------------------
        // FEES (VENDOR)
        // --------------------
        $total_service_fee = 0;
        $list_service_fee = null;

        if ($assistance->enable_service_fee && !empty($assistance->service_fee)) {
            $list_service_fee = $assistance->service_fee;
            $total_service_fee = $assistance->calculateServiceFees(
                $list_service_fee,
                $total_before_fees,
                $total_guests
            );
            $total += $total_service_fee;
        }

        // --------------------
        // BOOKING
        // --------------------
        $booking = new Booking();
        $booking->status        = 'draft';
        $booking->object_id    = $assistance->id;
        $booking->object_model = 'assistance';
        $booking->vendor_id    = $assistance->author_id;
        $booking->customer_id  = Auth::id();
        $booking->total        = $total;
        $booking->total_guests = $total_guests;

        $start_date = now();
        $booking->start_date = $start_date;
        $booking->end_date   = $start_date->copy()->addHours(max(1, $assistance->duration));

        $booking->vendor_service_fee_amount = $total_service_fee;
        $booking->vendor_service_fee        = $list_service_fee;
        $booking->buyer_fees                = $list_buyer_fees;
        $booking->total_before_fees         = $total_before_fees;
        $booking->total_before_discount     = $total_before_fees;

        if ($assistance->isFixedDate()) {
            $booking->start_date = $assistance->start_date;
            $booking->end_date   = $assistance->end_date;
        }

        $booking->calculateCommission();

        if (!$booking->save()) {
            return $this->sendError(__("Não foi possível criar a reserva"));
        }

        // --------------------
        // META
        // --------------------
        Booking::clearDraftBookings();

        $booking->addMeta('duration', $assistance->duration);
        $booking->addMeta('base_price', $base_price);

        if ($assistance->isFixedDate()) {
            $booking->addMeta('enable_fixed_date', 1);
            $booking->addMeta('fixed_date_data', [
                'start_date'        => $assistance->start_date,
                'end_date'          => $assistance->end_date,
                'last_booking_date' => $assistance->last_booking_date,
            ]);
        }

        BookingMessage::create([
            'booking_id' => $booking->id,
            'sender_id'  => Auth::id(),
            'message'    => "Olá! Acabei de solicitar a reserva. Aguardando confirmação do proprietário.",
        ]);

        event(new BookingConfirmEvent($booking));

        return redirect("/user/chat?bk={$booking->id}");
    }
}
