<?php
namespace Modules\Assistance\Controllers;

use Modules\Booking\Events\BookingUpdatedEvent;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\LocationCategory;
use Modules\Assistance\Hook;
use Modules\Assistance\Models\Assistance;
use Modules\Assistance\Models\AssistanceCategory;
use Modules\Assistance\Models\AssistanceTranslation;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Assistance\Models\AssistanceTerm;
use Modules\Booking\Models\Booking;

class ManageAssistanceController extends FrontendController
{
    protected $assistanceClass;
    protected $assistanceTranslationClass;
    protected $assistanceCategoryClass;
    protected $assistanceTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct()
    {
        $this->assistanceClass = Assistance::class;
        $this->assistanceTranslationClass = AssistanceTranslation::class;
        $this->assistanceCategoryClass = AssistanceCategory::class;
        $this->assistanceTermClass = AssistanceTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->bookingClass = Booking::class;
        parent::__construct();
    }

    public function callAction($method, $parameters)
    {
        if (setting_item('assistance_disable')) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function manageAssistance(Request $request)
    {
        $this->checkPermission('assistance_view');
        $user_id = Auth::id();
        $list_assistance = $this->assistanceClass::where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows'        => $list_assistance->paginate(5),
            'breadcrumbs' => [
                [
                    'name' => __('Gerenciar Serviços'),
                    'url'  => route('assistance.vendor.index'),
                ],
                [
                    'name'  => __('Todos'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Gerenciar Serviços"),
        ];
        return view('Assistance::frontend.manageAssistance.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('assistance_view');
        $user_id = Auth::id();
        $list_assistance = $this->assistanceClass::onlyTrashed()->where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows'        => $list_assistance->paginate(5),
            'recovery'           => 1,
            'breadcrumbs' => [
                [
                    'name' => __('Gerenciar Serviços'),
                    'url'  => route('assistance.vendor.index'),
                ],
                [
                    'name'  => __('Recuperação'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Recuperação Serviços"),
        ];
        return view('Assistance::frontend.manageAssistance.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('assistance_delete');
        $user_id = Auth::id();
        $query = $this->assistanceClass::onlyTrashed()->where("author_id", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
        }
        return redirect(route('assistance.vendor.recovery'))->with('success', __('Restauração do serviço bem-sucedida!'));
    }

    public function createAssistance(Request $request)
    {
        $this->checkPermission('assistance_create');
        $row = new $this->assistanceClass();
        $data = [
            'row'           => $row,
            'translation'   => new $this->assistanceTranslationClass(),
            'assistance_category' => $this->assistanceCategoryClass::get()->toTree(),
            'assistance_location' => $this->locationClass::where("status", "publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'assistance')->get(),
            'location_category'=>$this->locationCategoryClass::where("status", "publish")->get(),

            'breadcrumbs'   => [
                [
                    'name' => __('Gerenciar Serviços'),
                    'url'  => route('assistance.vendor.index'),
                ],
                [
                    'name'  => __('Criar'),
                    'class' => 'active'
                ],
            ],
            'page_title'    => __("Criar Serviços"),
        ];
        return view('Assistance::frontend.manageAssistance.detail', $data);
    }

    public function editAssistance(Request $request, $id)
    {
        $this->checkPermission('assistance_update');
        $user_id = Auth::id();
        $row = $this->assistanceClass::where("author_id", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('assistance.vendor.index'))->with('warning', __('Serviços não encontrados'));
        }
        $translation = $row->translate($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'            => $row,
            'assistance_category'  => $this->assistanceCategoryClass::where("status", "publish")->get()->toTree(),
            'assistance_location'  => $this->locationClass::where("status", "publish")->get()->toTree(),
            'location_category'=>$this->locationCategoryClass::where("status", "publish")->get(),
            'attributes'     => $this->attributesClass::where('service', 'assistance')->get(),
            "selected_terms" => $row->assistance_term->pluck('term_id'),
            'breadcrumbs'    => [
                [
                    'name' => __('Gerenciar Serviços'),
                    'url'  => route('assistance.vendor.index'),
                ],
                [
                    'name'  => __('Editar'),
                    'class' => 'active'
                ],
            ],
            'page_title'     => __("Editar Serviços"),
        ];
        return view('Assistance::frontend.manageAssistance.detail', $data);
    }

    public function store(Request $request, $id)
    {
        if(is_demo_mode()){
            return redirect()->back()->with('danger',__("MODO DEMO: não é possível adicionar dados"));
        }
        if ($id > 0) {
            $this->checkPermission('assistance_update');
            $row = $this->assistanceClass::find($id);
            if (empty($row)) {
                return redirect(route('assistance.vendor.edit', ['id' => $row->id]));
            }
            if ($row->author_id != Auth::id() and !$this->hasPermission('assistance_manage_others')) {
                return redirect(route('assistance.vendor.edit', ['id' => $row->id]));
            }
        } else {
            $this->checkPermission('assistance_create');
            $row = new $this->assistanceClass();
            $row->status = "publish";
            if (setting_item("assistance_vendor_create_service_must_approved_by_admin", 0)) {
                $row->status = "pending";
            }
            $row->author_id = Auth::id();
        }
        $row->fillByAttr([
            'title',
            'content',
            'image_id',
            'banner_image_id',
            'short_desc',
            'category_id',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'gallery',
            'video',
            'religion',
            'default_state',
            'price',
            'sale_price',
            'duration',
            'max_people',
            'min_people',
            'faqs',
            'include',
            'exclude',
            'itinerary',
            'enable_service_fee',
            'service_fee',
            'surrounding',
            'min_day_before_booking',
            'enable_fixed_date',
            'start_date',
            'end_date',
            'last_booking_date',

        ], $request->input());

        if(!auth()->user()->checkUserPlan() and $row->status == "publish") {
            return redirect(route('user.plan'));
        }
        $row->ical_import_url = $request->ical_import_url;
        $res = $row->saveOriginOrTranslation($request->input('lang'), true);
        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
                $row->saveMeta($request);
            }
            do_action(Hook::AFTER_SAVING,$row,$request);
            if ($id > 0) {
                return back()->with('success', __('Serviços atualizado'));
            } else {
                event(new CreatedServicesEvent($row));
                return redirect(route('assistance.vendor.edit', ['id' => $row->id]))->with('success', __('Serviços criado'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->assistanceTermClass::where('assistance_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->assistanceTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'assistance_id' => $row->id
                ]);
            }
            $this->assistanceTermClass::where('assistance_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function deleteAssistance($id)
    {
        $this->checkPermission('assistance_delete');
        $user_id = Auth::id();
        if(\request()->query('permanently_delete')){
            $query = $this->assistanceClass::where("author_id", $user_id)->where("id", $id)->withTrashed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        }else {
            $query = $this->assistanceClass::where("author_id", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
            }
        }
        return redirect(route('assistance.vendor.index'))->with('success', __('Exclusão do serviço bem-sucedida!'));
    }

    public function bulkEditAssistance($id, Request $request)
    {
        $this->checkPermission('assistance_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->assistanceClass::where("author_id", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('Nenhum item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Selecione uma ação!'));
        }
        if (empty($query)) {
            return redirect()->back()->with('error', __('Não encontrado'));
        }
        switch ($action) {
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                if(!auth()->user()->checkUserPlan() ) {
                    return redirect(route('user.plan'));
                }
                break;
        }
        $query->save();
        return redirect()->back()->with('success', __('Atualização bem-sucedida!'));
    }

    public function bookingReportBulkEdit($booking_id, Request $request)
    {
        $status = $request->input('status');
        if (!empty(setting_item("assistance_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if (!empty($item)) {
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();

                event(new BookingUpdatedEvent($item));
                return redirect()->back()->with('success', __('Atualização bem-sucedida'));
            }
            return redirect()->back()->with('error', __('Reserva não encontrada!'));
        }
        return redirect()->back()->with('error', __('Falha na atualização!'));
    }

    public function cloneAssistance(Request $request, $id)
    {
        $this->checkPermission('assistance_update');
        $user_id = Auth::id();
        $row = $this->assistanceClass::where("author_id", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('assistance.vendor.index'))->with('warning', __('Serviços não encontrados!'));
        };
        try {
            $clone = $row->replicate();
            $clone->status = 'draft';
            $clone->push();
            if (!empty($row->assistance_term)) {
                foreach ($row->assistance_term as $term) {
                    $e = $term->replicate();
                    if ($e->push()) {
                        $clone->assistance_term()->save($e);
                    }
                }
            }
            if (!empty($row->meta)) {
                $e = $row->meta->replicate();
                if ($e->push()) {
                    $clone->meta()->save($e);
                }
            }
            if (!empty($row->translations)) {
                foreach ($row->translations as $translation) {
                    $e = $translation->replicate();
                    $e->origin_id = $clone->id;
                    if ($e->push()) {
                        $clone->translations()->save($e);
                    }
                }
            }
            return redirect()->back()->with('success', __('O clone do serviço foi bem-sucedido'));
        } catch (\Exception $exception) {
            $clone->delete();
            return redirect()->back()->with('warning', __($exception->getMessage()));
        }
    }
}